### ISSUE TITLE
[Filebeat] conf.yaml.example is invalid

### ISSUE THREAD

**Issue by martonsz** [DataDog/integrations-extras#149]
The file `conf.yaml.example` for the [filebeat integration](https://github.com/DataDog/integrations-extras/blob/master/filebeat/conf.yaml.example) is invalid. 

If I understand the source code correctly it should be something like this:

 ```yaml
init_config:

instances:
  # Full path to filebeat registry file
  - registry_file_path: /path/to/filebeat/registry

 ```
