### ISSUE TITLE
Puma auto discovery

### ISSUE THREAD

**Issue by miguelaferreira** [DataDog/integrations-extras#2063]
This is a question, not a bug report, so I'll skip the standard template.

We run a few Puma based applications in containers on EKS. We have built our own image of the Datadog agent, that includes the Puma integration provided in this repo. For the configuration of the integration, it seems like we need to define all the puma instances for the agent to check them. However, since we run on containers we can't predict all the pods running Puma. Is there any way we could use auto discovery to configure the integration?

**Comment by miguelaferreira** [comment]
For anyone landing in this issue with the same type of question, we ended up configuring the integration using [Kubernetes Integration Autodiscovery](https://docs.datadoghq.com/containers/kubernetes/integrations/?tab=kubernetesadv2).

This is how we ended up writing our deployments to enable the integration.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  ...
spec:
  ...
  template:
    metadata:
      annotations:
        ad.datadoghq.com/main.checks: '{ "puma": { "init_config": { "service": "<SERVICE_NAME>"
          }, "instances": [{"control_url": "http://%%host%%:9293/stats?token=<SOME-TOKEN>"}]
          } }'
    spec:
      containers:
      - name: main
        ....
```

The one thing we are still looking into is how to not have to specify the token in the annotation.
