### ISSUE TITLE
redis_sentinel

### ISSUE THREAD

**Issue by melissa-hale** [DataDog/integrations-extras#2395]
**Output of the [info page](https://docs.datadoghq.com/agent/guide/agent-commands/#service-status)**

When running the redis_sentinel integration to monitor a group of Redis Sentinel servers, the check fails with the following error:

```text
2024-05-24 22:57:33 UTC | CORE | WARN | (pkg/collector/python/datadog_agent.go:131 in LogMessage) | redis_sentinel:e8118be2e61e206d | (redis_sentinel.py:42) | Error collecting metrics for master myprimary: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
```

This is my conf.yaml:

```yaml
init_config:

instances:
  - sentinel_host: ${{SENTINEL1_PRIVATE_DOMAIN}}
    sentinel_port: 26379
    sentinel_password: ${{REDIS_PRIMARY_PASSWORD}}
    masters:
      - ${{REDIS_PRIMARY_NAME}}
    tags:
      - instance:redis_sentinel_1
  - sentinel_host: ${{SENTINEL2_PRIVATE_DOMAIN}}
    sentinel_port: 26379
    sentinel_password: ${{REDIS_PRIMARY_PASSWORD}}
    masters:
      - ${{REDIS_PRIMARY_NAME}}
    tags:
      - instance:redis_sentinel_2
  - sentinel_host: ${{SENTINEL3_PRIVATE_DOMAIN}}
    sentinel_port: 26379
    sentinel_password: ${{REDIS_PRIMARY_PASSWORD}}
    masters:
      - ${{REDIS_PRIMARY_NAME}}
    tags:
      - instance:redis_sentinel_3
```

**Additional environment details (Operating System, Cloud provider, etc):**
- Deployed in a Docker environment
- Redis images tried: `redis:latest` & `redis:6.2.6`
- Agent image: `datadog/agent:7`
- Reproduced issue locally on Mac Sonoma

**Steps to reproduce the issue:**
1. Deploy a Redis replica set with Sentinel (followed [this guide](https://redis.io/learn/operate/redis-at-scale/high-availability/introduction))
2. Deploy a DataDog agent
3. Install integtation: `datadog-agent integration install -t datadog-redis_sentinel==1.1.0` (or 1.1.1) in agent container
4. Configure the redis_sentinel check similar to above and restart agent
5. Observe error upon check execution

**Describe the results you received:**
Received an AUTH error during check execution

**Describe the results you expected:**
For the check execution to complete successfully

**Additional information you deem important (e.g. issue happens only occasionally):**
I was able to fix this in the `redis_sentinel.py` by passing a username of "default" when initializing the redis connection with `redis.StrictRedis`, e.g. -
```python
redis_conn = redis.StrictRedis(host=host, port=port, username="default", password=password, db=0)
```
So I believe this is related to the [implementation of ACLs](https://redis.io/docs/latest/operate/oss_and_stack/management/security/acl/) after Redis version 5.  According to this doc, you can configure Redis to function the same as it did prior to the change, but I haven't been successful in getting any configuration changes on Redis side to work.

Happy to accept this is an issue I need to resolve in my Redis configuration, but in case others run into this, I figured it would be helpful to have a record either way.

Thanks!
