### ISSUE TITLE
can't see metrics for hbase_regionserver integration

### ISSUE THREAD

**Issue by amitdaniel86** [DataDog/integrations-extras#78]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```
 sudo /etc/init.d/datadog-agent status
Datadog Agent (supervisor) is running all child processes  [  OK  ]

sudo /etc/init.d/datadog-agent status -v ( only for the hbase section ) 

 hbase_regionserver (5.16.0)
    ---------------------------
      - instance #hbase_regionserver-127.0.0.1-9010 [OK] collected 13 metrics
      - Collected 13 metrics, 0 events & 0 service checks

```

**Additional environment details (Operating System, Cloud provider, etc):**
cloud provider - AWS
OS : CentOS release 6.8 (Final)

**Steps to reproduce the issue:**
1. just trying to get the hbase regionservers metrics .

**Describe the results you received:**
Empty metrics

**Describe the results you expected:**
get all the hbase metrics in my datadog account

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by jensendw** [comment]
@hush-hush @masci 
Is there any further information we can provide you for this to assist in testing.  We are seeing the following in the jmxfetch.log 
```
2017-08-15 20:07:06,992 | INFO | App | Instance hbase_regionserver-127.0.0.1-9010 is sending 13 metrics to the metrics reporter during collection #77150
2017-08-15 20:07:06,992 | DEBUG| Status | Writing status to temp yaml file: /opt/datadog-agent/run/jmx_status.yaml
2017-08-15 20:07:06,992 | DEBUG| App | Iteration ran in 2 ms
2017-08-15 20:07:06,992 | DEBUG| App | Sleeping for 15000 ms.
2017-08-15 20:07:21,996 | DEBUG| App | Instance hbase_regionserver-127.0.0.1-9010 is sending 13 metrics to the metrics reporter during collection #77151
2017-08-15 20:07:21,996 | DEBUG| Status | Writing status to temp yaml file: /opt/datadog-agent/run/jmx_status.yaml
2017-08-15 20:07:21,996 | DEBUG| App | Iteration ran in 4 ms
2017-08-15 20:07:21,996 | DEBUG| App | Sleeping for 15000 ms.
```

**Comment by jeremy-lq** [comment]
@everpeace is the maintainer for this integration and may also be able to provide some guidance.

**Comment by everpeace** [comment]
@amitdaniel86 @jensendw sorry for my absence.  

Those `13 metrics` would be `jvm` metrics.  Usually, more metrics should be collected.

To dig a reason,  

- Would you mind making sure that your __regionserver__ is up and jmx enabled on the port of `9010`.
- Could you share those below??
    - the output of `sudo /etc/init.d/datadog-agent jmx list_collected_attributes` and `sudo /etc/init.d/datadog-agent jmxlist_not_matching_attributes ` (refer to [the document](https://docs.datadoghq.com/integrations/java/#troubleshooting/))
    - your configuration file(`conf.yaml`)

If this integartion works well, you could see the output similar below:

```
$ datadog-agent jmx list_collected_attributes
#####################################
Instance: localhost:10102
#####################################

       Matching: 1/350. Bean name: java.lang:type=GarbageCollector,name=ParNew - Attribute name: CollectionCount  - Attribute type: long
       Matching: 2/350. Bean name: java.lang:type=GarbageCollector,name=ParNew - Attribute name: CollectionTime  - Attribute type: long
       Matching: 3/350. Bean name: java.lang:type=GarbageCollector,name=ConcurrentMarkSweep - Attribute name: CollectionCount  - Attribute type: long
       Matching: 4/350. Bean name: java.lang:type=GarbageCollector,name=ConcurrentMarkSweep - Attribute name: CollectionTime  - Attribute type: long
       Matching: 5/350. Bean name: Hadoop:service=HBase,name=JvmMetrics - Attribute name: MemNonHeapUsedM  - Attribute type: java.lang.Float
       Matching: 6/350. Bean name: Hadoop:service=HBase,name=JvmMetrics - Attribute name: MemNonHeapCommittedM  - Attribute type: java.lang.Float
       Matching: 7/350. Bean name: Hadoop:service=HBase,name=JvmMetrics - Attribute name: MemNonHeapMaxM  - Attribute type: java.lang.Float
       Matching: 8/350. Bean name: Hadoop:service=HBase,name=JvmMetrics - Attribute name: MemHeapUsedM  - Attribute type: java.lang.Float
       Matching: 9/350. Bean name: Hadoop:service=HBase,name=JvmMetrics - Attribute name: MemHeapCommittedM  - Attribute type: java.lang.Float
       Matching: 10/350. Bean name: Hadoop:service=HBase,name=JvmMetrics - Attribute name: MemHeapMaxM  - Attribute type: java.lang.Float
       Matching: 11/350. Bean name: Hadoop:service=HBase,name=JvmMetrics - Attribute name: MemMaxM  - Attribute type: java.lang.Float
       Matching: 12/350. Bean name: Hadoop:service=HBase,name=JvmMetrics - Attribute name: GcCountParNew  - Attribute type: java.lang.Long
       Matching: 13/350. Bean name: Hadoop:service=HBase,name=JvmMetrics - Attribute name: GcTimeMillisParNew  - Attribute type: java.lang.Long
       Matching: 14/350. Bean name: Hadoop:service=HBase,name=JvmMetrics - Attribute name: GcCountConcurrentMarkSweep  - Attribute type: java.lang.Long
       Matching: 15/350. Bean name: Hadoop:service=HBase,name=JvmMetrics - Attribute name: GcTimeMillisConcurrentMarkSweep  - Attribute type: java.lang.Long
       Matching: 16/350. Bean name: Hadoop:service=HBase,name=JvmMetrics - Attribute name: GcCount  - Attribute type: java.lang.Long
       Matching: 17/350. Bean name: Hadoop:service=HBase,name=JvmMetrics - Attribute name: GcTimeMillis  - Attribute type: java.lang.Long
       Matching: 18/350. Bean name: java.lang:type=Threading - Attribute name: ThreadCount  - Attribute type: int
       Matching: 19/350. Bean name: Hadoop:service=HBase,name=RegionServer,sub=IPC - Attribute name: queueSize  - Attribute type: java.lang.Long
       Matching: 20/350. Bean name: Hadoop:service=HBase,name=RegionServer,sub=IPC - Attribute name: numOpenConnections  - Attribute type: java.lang.Integer
       Matching: 21/350. Bean name: Hadoop:service=HBase,name=RegionServer,sub=IPC - Attribute name: numActiveHandler  - Attribute type: java.lang.Integer
       Matching: 22/350. Bean name: Hadoop:service=HBase,name=RegionServer,sub=IPC - Attribute name: TotalCallTime_max  - Attribute type: java.lang.Long
       Matching: 23/350. Bean name: Hadoop:service=HBase,name=RegionServer,sub=IPC - Attribute name: TotalCallTime_mean  - Attribute type: java.lang.Long
       Matching: 24/350. Bean name: Hadoop:service=HBase,name=RegionServer,sub=IPC - Attribute name: TotalCallTime_median  - Attribute type: java.lang.Long
       Matching: 25/350. Bean name: Hadoop:service=HBase,name=RegionServer,sub=IPC - Attribute name: TotalCallTime_99th_percentile  - Attribute type: java.lang.Long
       Matching: 29/350. Bean name: java.lang:type=Memory - Attribute name: HeapMemoryUsage  - Attribute type: javax.management.openmbean.CompositeData
       Matching: 33/350. Bean name: java.lang:type=Memory - Attribute name: NonHeapMemoryUsage  - Attribute type: javax.management.openmbean.CompositeData
```

**Comment by amitdaniel86** [comment]
@everpeace @jensendw 
Thanks for your response let me add all the details . 

Hbase version : 

```
> hbase shell
17/08/17 07:31:06 INFO Configuration.deprecation: hadoop.native.lib is deprecated. Instead, use io.native.lib.available
HBase Shell; enter 'help<RETURN>' for list of supported commands.
Type "exit<RETURN>" to leave the HBase Shell
Version 1.2.0-cdh5.8.3, rUnknown, Wed Oct 12 20:32:08 PDT 2016

```
```
sudo /etc/init.d/datadog-agent jmx list_collected_attributes

sudo /etc/init.d/datadog-agent jmx list_collected_attributes
2017-08-17 07:32:10,341 | WARNING | dd.collector | utils.dockerutil(dockerutil.py:94) | Error while detecting orchestrator: Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))
2017-08-17 07:32:10,353 | INFO | dd.collector | jmxfetch(jmxfetch.py:239) | Starting jmxfetch:
2017-08-17 07:32:10,353 | INFO | dd.collector | jmxfetch(jmxfetch.py:296) | Running java -Xms50m -Xmx200m -classpath /opt/datadog-agent/agent/checks/libs/jmxfetch-0.15.0-jar-with-dependencies.jar org.datadog.jmxfetch.App --check hbase_regionserver.yaml --check_period 15000 --conf_directory /etc/dd-agent/conf.d --log_level INFO --log_location /var/log/datadog/jmxfetch.log --reporter console --status_location /opt/datadog-agent/run/jmx_status.yaml list_collected_attributes

#####################################
Instance: 127.0.0.1:9010
#####################################

       Matching: 1/350. Bean name: java.lang:type=GarbageCollector,name=PS Scavenge - Attribute name: CollectionCount  - Attribute type: long
       Matching: 2/350. Bean name: java.lang:type=GarbageCollector,name=PS Scavenge - Attribute name: CollectionTime  - Attribute type: long
       Matching: 3/350. Bean name: java.lang:type=Threading - Attribute name: ThreadCount  - Attribute type: int
       Matching: 7/350. Bean name: java.lang:type=Memory - Attribute name: HeapMemoryUsage  - Attribute type: javax.management.openmbean.CompositeData
       Matching: 11/350. Bean name: java.lang:type=Memory - Attribute name: NonHeapMemoryUsage  - Attribute type: javax.management.openmbean.CompositeData
       Matching: 12/350. Bean name: java.lang:type=GarbageCollector,name=PS MarkSweep - Attribute name: CollectionCount  - Attribute type: long
       Matching: 13/350. Bean name: java.lang:type=GarbageCollector,name=PS MarkSweep - Attribute name: CollectionTime  - Attribute type: long

```
hbase_regionserver.yaml file

```
cat hbase_regionserver.yaml
instances:
  - host: 127.0.0.1
    port: 9010 # This is the JMX port on which HBase RegionServer exposes its metrics (usually 10102)
    tags:
      hbase: p3-regionserver
      # env: stage
      # newTag: test
    # user: username
    # password: password
    # process_name_regex: .*process_name.* # Instead of specifying a host and port or jmx_url, the agent can connect using the attach api.
    #                                      # This requires the JDK to be installed and the path to tools.jar to be set below.
    # tools_jar_path: /usr/lib/jvm/java-7-openjdk-amd64/lib/tools.jar # To be set when process_name_regex is set
    # name: hbase_master
    # # java_bin_path: /path/to/java # Optional, should be set if the agent cannot find your java executable
    # # java_options: "-Xmx200m -Xms50m" # Optional, Java JVM options
    # # trust_store_path: /path/to/trustStore.jks # Optional, should be set if ssl is enabled
    # # trust_store_password: password

init_config:
  is_jmx: true

  # Metrics collected by this check. You should not have to modify this.
...... ( all default ) 

```

this is the java variables for jmx : 

`-Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
`
I hope that's enough .
